### ISSUE TITLE
Genesis load error 

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-examples#12]
Loading genesis file 'genesis/reaction.g' is failing with this release. Following is the traceback.
The script is `snippets/savemodel.py`.

```
ReadKkit::setMethod: option  not known, using Exponential Euler (ee)
Traceback (most recent call last):
  File "snippets/savemodel.py", line 67, in <module>
    written = write('/model', 'testsave.g')
  File "/usr/lib/python2.7/site-packages/moose/genesis/_main.py", line 66, in write
    cmin,cmax,sceneitems = autoCoordinates(meshEntry,srcdesConnection)
  File "/usr/lib/python2.7/site-packages/moose/genesis/_main.py", line 278, in autoCoordinates
    position = nx.graphviz_layout(G, prog = 'dot')
  File "/usr/lib/python2.7/site-packages/networkx/drawing/nx_pydot.py", line 257, in graphviz_layout
    return pydot_layout(G=G,prog=prog,root=root,**kwds)
  File "/usr/lib/python2.7/site-packages/networkx/drawing/nx_pydot.py", line 277, in pydot_layout
    D=P.create_dot(prog=prog)
  File "/usr/lib/python2.7/site-packages/pydot.py", line 1802, in <lambda>
    lambda f=frmt, prog=self.prog : self.create(format=f, prog=prog))
  File "/usr/lib/python2.7/site-packages/pydot.py", line 2023, in create
    status, stderr_output) )
pydot.InvocationException: Program terminated with status: 1. stderr follows: Error: /tmp/tmpL19Zsb: syntax error in line 2 near ','
```

**Comment by dilawar** [comment]
6ebca4df fixed this,
