### ISSUE TITLE
Snippets/Izhikevich_with_synapse.py

### ISSUE THREAD

**Issue by malav4994** [BhallaLab/moose-examples#18]
Traceback (most recent call last):
  File "Izhikevich_with_synapse.py", line 133, in <module>
    model_dict = make_model()
  File "Izhikevich_with_synapse.py", line 110, in make_model
    synapse, spike_in = make_synapse('/model/synapse')
  File "Izhikevich_with_synapse.py", line 88, in make_synapse
    syn.synapse.num = 1
AttributeError: 'moose.SynChan' object has no attribute 'synapse'

**Comment by hrani** [comment]
@malav4994 this is already reported here #13 and what has to be done
