### ISSUE TITLE
clean up snippets wrt Rdesigneur and/or moogli

### ISSUE THREAD

**Issue by hrani** [BhallaLab/moose-examples#19]
- [x] testRdesigneur.py
 Warning: meshLambda argument is deprecated. Please use 'diffusionLength' instead. 
 For now rdesigneur will accept this argument. 
 Error: rdesigneur: Prototype build failed: "elec Proto: global function 'makeCellProto()' not known."

- [ ] testWigglySpines.py
NeuroMesh::updateShaftParents: may be misaligned
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

- [ ] rxdSpineSize.py
Warning: Dsolve::setNinit: Eref z out of range 1, 0
Traceback (most recent call last):
  File "rxdSpineSize.py", line 293, in <module>
    showVisualization()
  File "rxdSpineSize.py", line 191, in showVisualization
    makeModel()
  File "rxdSpineSize.py", line 120, in makeModel
    rdes.buildModel( '/model' )
  File "/home/harsha/Jan/moose-core/python/rdesigneur/rdesigneur.py", line 199, in buildModel
    self.buildAdaptors()
  File "/home/harsha/Jan/moose-core/python/rdesigneur/rdesigneur.py", line 489, in buildAdaptors
    self._buildAdaptor( mesh, i[2], i[3], name, i[1], False, i[4], i[5] )
  File "/home/harsha/Jan/moose-core/python/rdesigneur/rdesigneur.py", line 1230, in _buildAdaptor
    elecComptList = moose.vec( mesh.elecComptList[0].path + '/../spine' )
IndexError: tuple index out of range

**Comment by dilawar** [comment]
Both rxdSpineSize.py and testWigglySpine.py emit message `Not isModelfromKkit` and fails. Both are marked broken. See #30 . Closing it in favor of #30 .
