### ISSUE TITLE
Scripts that pass on travis or locally 

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-examples#4]
Travis tests each script in this directory. Not all scripts are run. Any script which launches GUI is not executed. Any script which has a call to `input()` or `raw_input()` won't run.
# Scripts that passed
- [x] ./../squid/squid.py
- [x] ./../squid/squid_setup.py
- [x] ./../MemoryNetworks/bidirectional_plastic_switch.py
- [x] ./../passive/passive_soma.py
- [x] ./../snippets/stochasticLotkaVolterra.py
- [x] ./../snippets/RandSpikeStats.py
- [x] ./../snippets/changeFuncExpression.py
- [x] ./../snippets/findChemSteadyState.py
- [x] ./../snippets/funcReacLotkaVolterra.py
- [x] ./../snippets/bidirectionalPlasticity.py
- [x] ./../snippets/hhcomp.py
- [x] ./../snippets/interpol2d.py
- [x] ./../snippets/pyrun1.py
- [x] ./../snippets/HsolveInstability.py
- [x] ./../snippets/scriptGssaSolver.py
- [x] ./../snippets/tabledemo.py
- [x] ./../snippets/startstop.py
- [x] ./../snippets/multiComptSigNeur.py
- [x] ./../snippets/synapse.py
- [x] ./../snippets/neuronFromDotp.py
- [x] ./../snippets/onetoonemsg.py
- [x] ./../snippets/compartment_net_no_array.py
- [x] ./../snippets/crossComptSimpleReac.py
- [x] ./../snippets/funcInputToPools.py
- [x] ./../snippets/compartment_net.py
- [x] ./../snippets/randomspike.py
- [x] ./../snippets/stimtable.py
- [x] ./../snippets/wildcard.py
- [x] ./../snippets/scriptKineticSolver.py
- [x] ./../snippets/tweakingParameters.py
- [x] ./../snippets/helloMoose.py
- [x] ./../snippets/traub_naf.py
- [x] ./../snippets/timetable.py
- [x] ./../snippets/singlemsgcross.py
- [x] ./../snippets/vclamp.py
- [x] ./../snippets/analogStimTable.py
- [x] ./../snippets/multicomp_lif.py
- [x] ./../snippets/gapjunction.py
- [x] ./../snippets/crossComptSimpleReacGSSA.py
- [x] ./../snippets/symcompartment.py
- [x] ./../snippets/scriptKineticModel.py
- [x] ./../snippets/intfire.py
- [x] ./../snippets/twocells.py
- [x] ./../snippets/reacDiffConcGradient.py
- [x] ./../snippets/lif.py
- [x] ./../snippets/func.py
- [x] ./../snippets/crossComptOscillator.py
- [x] ./../snippets/cylinderMotor.py
- [x] ./../snippets/loadCspaceModel.py
- [x] ./../snippets/cspaceSteadyState.py
- [x] ./../snippets/loadKineticModel.py
- [x] ./../snippets/hdfdemo.py
- [x] ./../snippets/testHsolve.py
- [x] ./../snippets/loadSbmlmodel.py
- [x] ./../snippets/savemodel.py
- [x] ./../snippets/switchKineticSolvers.py
- [x] ./../snippets/chemDoseResponse.py
- [x] ./../snippets/convert_Genesis2Sbml.py
- [x] ./../snippets/multiscaleOneCompt.py
- [x] ./../snippets/nsdf.py
- [x] ./../snippets/function.py
- [x] ./../snippets/ionchannel.py
- [x] ./../snippets/cubeMeshSigNeur.py
- [x] ./../snippets/STDP.py
- [x] ./../snippets/funcRateHarmonicOsc.py
- [x] ./../snippets/threading_demo.py
- [x] ./../snippets/diffEqSolution.py
- [x] ./../snippets/mgblock.py
- [x] ./../snippets/pulsegen.py
- [x] ./../snippets/pyrun.py
- [x] ./../kinetics/test_ksolve.py
- [x] ./../tutorials/ExcInhNetCaPlasticity/ExcInhNet_HigginsGraupnerBrunel2014.py
- [x] ./../tutorials/ChemicalOscillators/relaxationOsc.py
- [x] ./../tutorials/ChemicalOscillators/repressillator.py
- [x] ./../tutorials/ChemicalOscillators/slowFbOsc.py
- [x] ./../tutorials/ChemicalBistables/findSteadyState.py
- [x] ./../tutorials/ChemicalBistables/simpleBis.py
- [x] ./../tutorials/ChemicalBistables/doseResponse.py
- [x] ./../tutorials/ChemicalBistables/mapkFB.py
- [x] ./../tutorials/ChemicalBistables/strongBis.py
- [x] ./../tutorials/ExcInhNet/ExcInhNet_Ostojic2014_Brunel2000.py
- [x] ./../rall_1964/rall64.py
- [x] ./../neuroml/lobster_pyloric/STG_net.py
- [x] ./../neuroml/lobster_pyloric/channels/ChannelTest.py
- [x] ./../neuroml/LIF/twoLIFxml_firing.py
- [x] ./../neuroml/LIF/LIFxml_firing.py
- [x] ./../neuroml/CA1PyramidalCell/CA1_hsolve.py
- [x] ./../neuroml/CA1PyramidalCell/CA1.py
- [x] ./../neuroml/GranuleCell/Granule98_hsolve.py
- [x] ./../neuroml/GranuleCell/Granule98.py
- [x] ./../neuroml/allChannelsCell/allChannelsCell.py
- [x] ./../unsorted/ksolve_with_heavy_load.py
- [x] ./../symcomp/symcomp.py
- [x] ./../symcomp/symcomp_readcell.py
- [x] ./../snippets/lifcomp.py
# Scripts that failed
- [x] ./../paper-2015/Fig2_elecModels/Fig2A.py, Takes too much time, return 137. Not considering a failure now. It runs locally.
- [x] ./../snippets/nsdf_vec.py

```
|| Failed with status 1 
  Starting simulation at: 2016-05-06T12:45:05.717483
  Finished simulation at: 2016-05-06T12:45:05.873813
  Closing nsdf handle
  Closed nsdf handle
  Traceback (most recent call last):
    File "nsdf_vec.py", line 178, in <module>
      fname = write_nsdf()
    File "nsdf_vec.py", line 146, in write_nsdf
      pulse_info['delay', ii] = pulsegen.vec[ii].delay[0]
    File "/usr/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 359, in __setitem__
      raise TypeError("Field name selections are not allowed for write.")
  TypeError: Field name selections are not allowed for write.
```
# Script that did not executed for testing

Rest of them.

**Comment by dilawar** [comment]
@subhacom  Have  a look at `snippets/nsdf_vec.py` . The package `h5py` on 12.04 (Travis) is pretty old. If there is a way to fix this on Travis, I wont'  disable it.

**Comment by dilawar** [comment]
Since `ubuntu-12.04` is too old, we are not supporting it anymore. Travis has moved to 14.04 where this scripts passes.
