### ISSUE TITLE
Failure when running snippets/loadSbmlmodel.py

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-examples#9]
Travis reported the following problem:

````
```

  No CPU information available. Assuming single core.

  No CPU information available. Assuming single core.

  on node 0, numNodes = 1, numCores = 1

  Traceback (most recent call last):

    File "loadSbmlmodel.py", line 106, in <module>

      modelPath, modelpathexist = main()

    File "loadSbmlmodel.py", line 74, in main

      if sbmlId.path != '/':

  AttributeError: 'tuple' object has no attribute 'path'

```

**Comment by dilawar** [comment]
282955a8 and related commit fixed this,
